AllCops:
  TargetRubyVe# rubocop.yml

# AllCops settings apply globally
AllCops:
  TargetRubyVersion: 1.9
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'app/services/api/v1/statistics_service.rb'

Metrics/LineLength:
  Enabled: false

Rails:
  Enabled: true

Rails/ActionFilter:
  Enabled: false

Performance/RedundantMerge:
  Enabled: true
Performance/UnfreezeString:
  Enabled: true
Performance/Casecmp:
  Enabled: true
