default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME_DEVELOPMENT"] %>

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] %>

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME_PRODUCTION"] %>